- name: Install wireguard
  become: true
  apt:
    name: wireguard
    state: present

- name: Enable ip forwarding (might need server restart)
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^#?net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"

- name: Copy config for wg0
  become: true
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    backup: true
    mode: "0700"

- name: Copy over post up/post down files
  become: true
  template:
    src: "{{ item }}"
    dest: "/etc/wireguard/{{ item }}"
    mode: "0755"
    backup: true
  loop:
    - postup.sh
    - postdown.sh

- name: Setup/restart service for wg0
  become: true
  systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true

