# name: copy over nextcloud config
# template:
#   src: nextcloud/config.php.j2
#   dest: "{{ docker_data_path }}/nextcloud/config/config.php"
#   mode: "0640"
#   owner: www-data
#   group: www-data

- name: deploy nextcloud container
  become: true
  community.docker.docker_container:
    name: some-nextcloud-container
    image: "nextcloud:32-apache"
    state: started
    restart_policy: always
    networks:
      - name: db_network
      - name: proxy_network
      - name: cache_network
    volumes:
      - "{{ docker_data_path }}/nextcloud:/var/www/html"
    # comment for first run setup
    env:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: "{{ vault_mysql_nextcloud_password }}"
      MYSQL_HOST: some-mariadb-container

      NEXTCLOUD_ADMIN_USER: "{{ vault_nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ vault_nextcloud_admin_password }}"

      REDIS_HOST: some-redis-container
      REDIS_HOST_PASSWORD: "{{ redis_password }}"
