---

- name: Install ssmtp
  become: true
  ansible.builtin.apt:
      name: "{{ item }}"
      state: present
  with_items:
    - ssmtp
    - mailutils

- name: Copy ssmtp config files
  become: true
  ansible.builtin.template:
      src: "{{ item }}.j2"
      dest: "/etc/ssmtp/{{ item }}"
      owner: root
      group: root
  with_items:
      - revaliases
      - ssmtp.conf

- name: Add cron weekly email
  ansible.builtin.cron:
      name: "Weekly email"
      job: 'echo $(uptime) | mail -s "$(date)" {{ vault_email_address }}'
      special_time: weekly
      state: present
