
- name: Install latest rclone
  ansible.builtin.apt:
    deb: https://downloads.rclone.org/rclone-current-linux-amd64.deb

- name: Copy config file
  ansible.builtin.template:
    src: rclone.conf.j2
    dest: "{{ scripts_dir }}/rclone.conf"
    owner: "{{ rclone_owner }}"
    group: "{{ rclone_group }}"
    mode: "{{ rclone_config_mode }}"
