
- name: Install docker
  ansible.builtin.include_role:
    name: geerlingguy.docker

    apply:
      become: true

- name: Install miniconda
  ansible.builtin.include_role:
    name: andrewrothstein.miniconda
  vars:
    miniconda_ver: '4.8.2'
    miniconda_python_ver: '37'
    miniconda_parent_dir: /opt

- name: Install conda packages
  become: true
  ansible.builtin.shell:
    cmd: "/opt/anaconda/bin/conda install -y {{ item }} -c conda-forge"
  loop:
    - ansible
    - molecule
    - ipython
    - boto3
