- name: Add docker gpg keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install prerequiste packages
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "gnupg2"
      - "software-properties-common"
      - "python3-pip"
      - "python3-docker"

    state: present
    update_cache: true

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    filename: docker

- name: Install docker packages
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Start docker
  systemd:
    name: docker
    state: started
