- name: make data dir
  file:
    path: "{{ docker_data_path }}/redis"
    recurse: true
    state: directory
    owner: root
    group: root

- name: deploy redis container
  docker_container:
    name: some-redis-container
    image: "redis:7.2"
    command: "redis-server --requirepass {{ vault_redis_password }}"
    state: started
    restart: true
    restart_policy: always
    networks:
      - name: cache_network
