- name: deploy apache2 container without SSL
  community.docker.docker_container:
    name: some-apache2-container-nossl
    image: "docker-apache2-ssl:latest"
    state: started
    recreate: true
    restart_policy: always
    pull: false # build locally
    networks:
      - name: proxy_network
    published_ports:
      - 80:80

