---
- name: Create qbtuser user
  ansible.builtin.user:
    name: qbtuser
    password: '!'
    state: present
    system: true

- name: Install package
  ansible.builtin.apt:
      name: "qbittorrent-nox"
      state: present

- name: Create config dir
  ansible.builtin.file:
    path: "/home/qbtuser/.config/qBittorrent"
    state: directory
    owner: qbtuser
    group: qbtuser

- name: Copy config file
  ansible.builtin.template:
    src: "qBittorrent.conf.j2"
    dest: "/home/qbtuser/.config/qBittorrent/qBittorrent.conf"
    owner: qbtuser
    group: qbtuser

- name: Copy systemd file
  ansible.builtin.template:
    src: "qbittorrent-nox@.service.j2"
    dest: "/etc/systemd/system/qbittorrent-nox@.service"

- name: Enable service for user
  ansible.builtin.systemd:
    name: "qbittorrent-nox@qbtuser"
    state: started
    enabled: true
